from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget
import sys, Media_rc


class Ui_Success(QWidget):
    def __init__(self):
        super().__init__()
        self.resize(492, 271)
        self.widget = QtWidgets.QWidget(self)
        self.setWindowIcon(QtGui.QIcon(":/IMG/img/icons/ok.png"))
        self.widget.setGeometry(QtCore.QRect(10, 50, 461, 131))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.Line_FromAddr = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Line_FromAddr.sizePolicy().hasHeightForWidth())
        self.Line_FromAddr.setSizePolicy(sizePolicy)
        self.Line_FromAddr.setStyleSheet("border: 1px solid #bababa;\n"
                                         "border-radius: 7px;\n"
                                         "background-color: #fff;\n"
                                         "background-color: qlineargradient(spread:pad, x1:0.495, y1:0.431818, x2:0.516773, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 0));")
        self.Line_FromAddr.setObjectName("Line_FromAddr")
        self.gridLayout.addWidget(self.Line_FromAddr, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.Line_ToAddr = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Line_ToAddr.sizePolicy().hasHeightForWidth())
        self.Line_ToAddr.setSizePolicy(sizePolicy)
        self.Line_ToAddr.setStyleSheet("border: 1px solid #bababa;\n"
                                       "border-radius: 7px;\n"
                                       "background-color: #fff;\n"
                                       "background-color: qlineargradient(spread:pad, x1:0.495, y1:0.431818, x2:0.516773, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 0));")
        self.Line_ToAddr.setObjectName("Line_ToAddr")
        self.gridLayout.addWidget(self.Line_ToAddr, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.Line_Amount = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Line_Amount.sizePolicy().hasHeightForWidth())
        self.Line_Amount.setSizePolicy(sizePolicy)
        self.Line_Amount.setStyleSheet("border: 1px solid #bababa;\n"
                                       "border-radius: 7px;\n"
                                       "background-color: #fff;\n"
                                       "background-color: qlineargradient(spread:pad, x1:0.495, y1:0.431818, x2:0.516773, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 0));")
        self.Line_Amount.setObjectName("Line_Amount")
        self.gridLayout.addWidget(self.Line_Amount, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.Line_Txid = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Line_Txid.sizePolicy().hasHeightForWidth())
        self.Line_Txid.setSizePolicy(sizePolicy)
        self.Line_Txid.setStyleSheet("border: 1px solid #bababa;\n"
                                     "border-radius: 7px;\n"
                                     "background-color: #fff;\n"
                                     "background-color: qlineargradient(spread:pad, x1:0.495, y1:0.431818, x2:0.516773, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 0));")
        self.Line_Txid.setObjectName("Line_Txid")
        self.gridLayout.addWidget(self.Line_Txid, 3, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.Button_Copy_FromAddr = QtWidgets.QPushButton(self.widget)
        self.Button_Copy_FromAddr.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/IMG/img/icons/copy.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Button_Copy_FromAddr.setIcon(icon)
        self.Button_Copy_FromAddr.setObjectName("Button_Copy_FromAddr")
        self.gridLayout.addWidget(self.Button_Copy_FromAddr, 0, 2, 1, 1)
        self.Button_Copy_ToAddr = QtWidgets.QPushButton(self.widget)
        self.Button_Copy_ToAddr.setText("")
        self.Button_Copy_ToAddr.setIcon(icon)
        self.Button_Copy_ToAddr.setObjectName("Button_Copy_ToAddr")
        self.gridLayout.addWidget(self.Button_Copy_ToAddr, 1, 2, 1, 1)
        self.Button_Copy_Txid = QtWidgets.QPushButton(self.widget)
        self.Button_Copy_Txid.setText("")
        self.Button_Copy_Txid.setIcon(icon)
        self.Button_Copy_Txid.setObjectName("Button_Copy_Txid")
        self.gridLayout.addWidget(self.Button_Copy_Txid, 3, 2, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self)
        self.widget_2.setGeometry(QtCore.QRect(10, 189, 461, 61))
        self.widget_2.setObjectName("widget_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Button_Close = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Close.sizePolicy().hasHeightForWidth())
        self.Button_Close.setSizePolicy(sizePolicy)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/IMG/img/icons/delete.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Button_Close.setIcon(icon1)
        self.Button_Close.setObjectName("Button_Close")
        self.horizontalLayout.addWidget(self.Button_Close)
        spacerItem = QtWidgets.QSpacerItem(79, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Button_Save = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_Save.sizePolicy().hasHeightForWidth())
        self.Button_Save.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/IMG/img/icons/save.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Button_Save.setIcon(icon2)
        self.Button_Save.setObjectName("Button_Save")
        self.horizontalLayout.addWidget(self.Button_Save)
        self.Button_OK = QtWidgets.QPushButton(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Button_OK.sizePolicy().hasHeightForWidth())
        self.Button_OK.setSizePolicy(sizePolicy)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/IMG/img/icons/yes.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.Button_OK.setIcon(icon3)
        self.Button_OK.setObjectName("Button_OK")
        self.horizontalLayout.addWidget(self.Button_OK)
        self.textBrowser = QtWidgets.QTextBrowser(self)
        self.textBrowser.setGeometry(QtCore.QRect(5, 5, 481, 251))
        self.textBrowser.setStyleSheet("border: 1px solid #bababa;\n"
                                       "border-radius: 7px;\n"
                                       "background-color: #fff;\n"
                                       "background-color: qlineargradient(spread:pad, x1:0.495, y1:0.431818, x2:0.516773, y2:1, stop:0 rgba(255, 255, 255, 255), stop:1 rgba(255, 255, 255, 0));")
        self.textBrowser.setReadOnly(True)
        self.textBrowser.setObjectName("textBrowser")
        self.label_5 = QtWidgets.QLabel(self)
        self.label_5.setGeometry(QtCore.QRect(70, 15, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(84, 167, 111);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self)
        self.label_6.setGeometry(QtCore.QRect(43, 20, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(84, 167, 111);")
        self.label_6.setText("")
        self.label_6.setPixmap(QtGui.QPixmap(":/IMG/img/icons/ok.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setObjectName("label_6")
        self.textBrowser.raise_()
        self.widget.raise_()
        self.widget_2.raise_()
        self.label_5.raise_()
        self.label_6.raise_()
        self.Button_OK.clicked.connect(self.OnClose)
        self.Button_Save.clicked.connect(self.OnSave)
        self.Button_Close.clicked.connect(self.OnClose)
        self.textBrowser.setReadOnly(True)
        self.Button_Copy_Txid.clicked.connect(self.OnCopy)
        self.retranslateUi(self)
        QtCore.QMetaObject.connectSlotsByName(self)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        self.setWindowTitle(_translate("Form", "Successfully Transferred"))
        self.label_2.setText(_translate("Form", "TO"))
        self.label_3.setText(_translate("Form", "Amount"))
        self.label_4.setText(_translate("Form", "TXID"))
        self.label.setText(_translate("Form", "FROM"))
        self.Button_Close.setText(_translate("Form", "Close"))
        self.Button_Save.setText(_translate("Form", "Save"))
        self.Button_OK.setText(_translate("Form", "OK"))
        self.label_5.setText(_translate("Form", "Successfully Transferred"))

    def OnClose(self):
        self.close()

    def OnSave(self):
        fromAddr = self.Line_FromAddr.text()
        toAddr = self.Line_ToAddr.text()
        amount = self.Line_Amount.text()
        txid = self.Line_Txid.text()
        fw = open('Transaction_Details.txt', 'a')
        fw.write(f"From Address: {fromAddr}\n"
                 f"To Address : {toAddr}\n"
                 f"Amount : {amount}\n"
                 f"Transaction ID: {txid}\n"
                 f"{'-' * 66}\n")
        fw.close()
        self.close()

    def OnCopy(self):
        if self.Button_Copy_Txid:
            txs = self.Line_Txid.text()
            clip = QApplication.clipboard()
            clip.setText(txs)
            self.Button_Copy_Txid.setToolTip(f"Copy Successfully")



if __name__ == "__main__":
    app = QApplication(sys.argv)
    uiSucc = Ui_Success()
    uiSucc.show()
    sys.exit(app.exec_())
